# Generated by Django 6.0.7 on 2026-07-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_venda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_minima',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICAMENTO', 'Medicamento'), ('VACINA', 'Vacina'), ('MATERIAL_ESCRITORIO', 'Material de escritório'), ('MATERIAL_LIMPEZA', 'Material de limpeza'), ('OUTRO', 'Outro')], default='OUTRO', help_text='Define quais campos aparecem no cadastro de produtos desta categoria.', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Deixe em branco para itens sem validade (ex: materiais).', null=True, verbose_name='Data de validade'),
        ),
        migrations.AddField(
            model_name='produto',
            name='lote',
            field=models.CharField(blank=True, help_text='Número do lote (comum em vacinas e medicamentos).', max_length=50, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Pacote'), ('KG', 'Quilograma'), ('L', 'Litro'), ('ML', 'Mililitro'), ('DS', 'Dose'), ('FR', 'Frasco'), ('AMP', 'Ampola'), ('PAR', 'Par')], default='UN', max_length=3, verbose_name='Unidade de medida'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, help_text='Nem todo item precisa de código (ex: alimentos a granel).', max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
