# Generated by Django 6.0.7 on 2026-07-29 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_produto_preco_venda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('POSTO_SAUDE', 'Posto de Saúde'), ('SECRETARIA', 'Secretaria'), ('OUTRO', 'Outro')], default='POSTO_SAUDE', max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_custo',
        ),
        migrations.AddField(
            model_name='produto',
            name='detalhes',
            field=models.CharField(blank=True, help_text='Cor, tamanho, modelo, concentração, etc. Ex: "500mg/5ml" ou "Tamanho M, azul".', max_length=255, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICAMENTO', 'Medicamento'), ('VACINA', 'Vacina'), ('MATERIAL_ODONTOLOGICO', 'Material Odontológico'), ('MATERIAL_LIMPEZA', 'Material de Limpeza'), ('INSUMO', 'Insumo'), ('OUTRO', 'Outro')], default='OUTRO', help_text='Controla quais campos aparecem no cadastro de produtos desta categoria.', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo / Observação'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Deixe em branco para itens sem prazo de validade.', null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição / Observações'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='lote',
            field=models.CharField(blank=True, help_text='Número do lote (vacinas e medicamentos).', max_length=50, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Código interno ou de referência (opcional).', max_length=50, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Pacote'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('DS', 'Dose'), ('FR', 'Frasco'), ('AMP', 'Ampola'), ('PAR', 'Par'), ('RO', 'Rolo'), ('SC', 'Saco')], default='UN', max_length=3, verbose_name='Unidade de Medida'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('unidade', models.ForeignKey(blank=True, help_text='Deixe em branco para conceder acesso de Administrador (vê todas as unidades).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='estoque.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque.unidade', verbose_name='Unidade'),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
