# Generated by Django 5.2.17 on 2026-09-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_categoria_material_hospitalar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICAMENTO', 'Medicamento'), ('VACINA', 'Vacina'), ('MATERIAL_ODONTOLOGICO', 'Material Odontológico'), ('MATERIAL_HOSPITALAR', 'Material Hospitalar'), ('MATERIAL_LIMPEZA', 'Material de Limpeza'), ('INSUMO', 'Insumo'), ('OUTRO', 'Outro')], default='OUTRO', help_text='Controla quais campos aparecem no cadastro de produtos desta categoria.', max_length=30, verbose_name='Tipo'),
        ),
    ]
