# Generated by Django 6.0.7 on 2026-10-04 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_categoria_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Pacote'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('DS', 'Dose'), ('FR', 'Frasco'), ('AMP', 'Ampola'), ('PAR', 'Par'), ('RO', 'Rolo'), ('SC', 'Saco'), ('FD', 'Fardo')], default='UN', max_length=3, verbose_name='Unidade de Medida'),
        ),
        migrations.CreateModel(
            name='ImportacaoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(unique=True, verbose_name='Código da requisição')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('solicitante', models.CharField(blank=True, max_length=150, verbose_name='Solicitante')),
                ('data_solicitacao', models.DateField(blank=True, null=True, verbose_name='Data da requisição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_requisicao', to='estoque.unidade', verbose_name='Unidade de destino')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Importação de Requisição',
                'verbose_name_plural': 'Importações de Requisição',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DivergenciaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTOQUE_INSUFICIENTE', 'Estoque do sistema menor que o entregue'), ('UNIDADE_MEDIDA_DIFERENTE', 'Unidade de medida diferente (baixa não feita)')], max_length=30, verbose_name='Tipo')),
                ('quantidade_entregue', models.PositiveIntegerField(verbose_name='Quantidade entregue')),
                ('unidade_medida_entregue', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Pacote'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('DS', 'Dose'), ('FR', 'Frasco'), ('AMP', 'Ampola'), ('PAR', 'Par'), ('RO', 'Rolo'), ('SC', 'Saco'), ('FD', 'Fardo')], max_length=3, verbose_name='Unidade de medida entregue')),
                ('quantidade_sistema', models.PositiveIntegerField(verbose_name='Quantidade no sistema (antes da baixa)')),
                ('quantidade_baixada', models.PositiveIntegerField(default=0, verbose_name='Quantidade baixada')),
                ('resolvida', models.BooleanField(default=False, verbose_name='Resolvida')),
                ('resolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrada em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='estoque.produto', verbose_name='Produto (estoque central)')),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divergencias_resolvidas', to=settings.AUTH_USER_MODEL, verbose_name='Resolvida por')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='estoque.importacaorequisicao', verbose_name='Importação de origem')),
            ],
            options={
                'verbose_name': 'Divergência de Estoque',
                'verbose_name_plural': 'Divergências de Estoque',
                'ordering': ['resolvida', '-criado_em'],
            },
        ),
    ]
