# Generated by Django 6.0.7 on 2026-10-05 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_importacao_requisicao_divergencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RascunhoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('solicitante', models.CharField(blank=True, max_length=150, verbose_name='Solicitante')),
                ('data_solicitacao', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('itens', models.JSONField(blank=True, default=list, verbose_name='Itens')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rascunhos_requisicao', to='estoque.unidade', verbose_name='Unidade solicitante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rascunhos_requisicao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Rascunho de Requisição',
                'verbose_name_plural': 'Rascunhos de Requisição',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
